development:
  secret_token: ENV['SECRET_TOKEN']
  secret_key_base: ENV['SECRET_KEY']

test:
  secret_token: ENV['SECRET_TOKEN']
  secret_key_base: ENV['SECRET_KEY']

production:
  secret_token: ENV['SECRET_TOKEN']
  secret_key_base: ENV['SECRET_KEY']


# devise_secret_key: <%= ENV['DEVISE_KEY'] %>

# SECRET_TOKEN=my_secret_token
# SECRET_KEY=abcdef0123456789

# ENV['ADMIN_NAME']